project_name: nytaxi
databases:
    - name: nytaxi
      type: postgres
      host: localhost
      port: 5432
      database: nytaxi
      user: postgres
      password: ${POSTGRES_PASSWORD}
      schema_name: public
      accessors:
          - columns
          - preview
          - description
      include: []
      exclude: []
repos: []
notion: null
llm:
    provider: openai
    api_key: ${OPENAI_API_KEY}
slack: null
mcp: null
